### ISSUE TITLE
修改ructhesis.cls以解决独创性声明页面字体不一致，并且在此页面自动填上作者和日期

### ISSUE THREAD

**Issue by whpxg** [GH1995/RUC-thesis-template-for-LaTeX#2]
如题。

以下为修改好之后的文件
[ructhesis.zip](https://github.com/GH1995/RUC-thesis-template-for-LaTeX/files/1828975/ructhesis.zip)

**Comment by leftrk** [comment]
收到，欢迎PR。

**Comment by ghost** [comment]
谢谢贡献
