### ISSUE TITLE
副标题生成无效

### ISSUE THREAD

**Issue by ghost** [GH1995/RUC-thesis-template-for-LaTeX#5]
本科毕业论文 \subtitle 填充内容后编译无效

**Comment by ghost** [comment]
找到解决办法了，打开 ructhesis.cls 文件，找到下面这行
`\zihao{2}\@subtitletrue\par\vskip\stretch{1}\zihao{3}`
改成
`\zihao{2}\@subtitle\par\vskip\stretch{1}\zihao{3}`

**Comment by leftrk** [comment]
好的，谢谢你，可以发一下`pull request`吗？

**Comment by ghost** [comment]
git 新手，pr 等摸索明白过一阵再发，因为我发现 2017 年修订本科生指导手册与之前的要求有许多地方不一样，我现在在修改，之后发一份最新版 pr
