### ISSUE TITLE
百度网盘下载的字体应该放在哪个目录？

### ISSUE THREAD

**Issue by JieGenius** [GH1995/RUC-thesis-template-for-LaTeX#8]
grep: OT.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT' failed to make OT.tfm.
kpathsea: Running mktextfm SimSun/OT
/usr/local/texlive/2021/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT. /usr/local/texlive/2021/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2021/texmf-dist/fonts/map/fontname/special.map?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input OT
This is METAFONT, Version 2.71828182 (TeX Live 2021) (preloaded base=mf)
kpathsea: Running mktexmf OT

目前报这样的错误，推测是字体原因导致的，但是不知道字体要放到哪个目录

**Comment by leftrk** [comment]
参考这里 https://superuser.com/questions/137826/location-of-truetype-fonts @JieGenius

**Comment by JieGenius** [comment]
> 参考这里 https://superuser.com/questions/137826/location-of-truetype-fonts @JieGenius

谢谢，我已经解决了。我使用的是mac电脑，直接双击.ttf文件就会自动安装，不需要手动复制到某个路径。
README链接中提供的字体并不能解决我的问题，根据错误 `Running mktextfm SimSun/OT`,我安装了SimSun字体，SimHei，FangSong这三款字体后成功编译tex。 
附三款字体的链接 [SimSun(宋体)](https://www.wfonts.com/download/data/2015/08/10/simsun/simsun.zip)，[SimHei(黑体)](https://www.wfonts.com/download/data/2014/06/01/simhei/simhei.zip), [FangSong(仿宋)](https://www.wfonts.com/download/data/2014/06/01/fangsong/fangsong.zip)
